### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by zzs95** [QtacierP/PRIOR#3]
I want to try the [Zero-shot classification](https://github.com/QtacierP/PRIOR#zero-shot-classification) part, however the code of  ZeroShotClassificationModel (prior.downstream.zero_classification_model.ZeroShotClassificationModel) seems to be missing.

**Comment by QtacierP** [comment]
I  am sorry for the late reply, due to the inconvenience caused by recently updating my email address, which may have resulted in missing some GitHub notifications. Due to a version conflict, I inadvertently omitted the code for the zero-shot model in my previous upload. However, I have now made the necessary updates. If you have any questions or encounter any issues, please feel free to ask. Thank you :)
